{
 "title": "Outbuild API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Api Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "count(rate({job=\"api\"} | json | req_method =~ `.+` [1m]))"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"api\"} | json | req_method =~ `.+` | line_format `Request: {{.req_method}} {{.req_url}} | StatusCode: {{.res_statusCode}} | ResponseTime: {{.responseTime}}ms `"
    }
   ]
  },
  {
   "title": "API Response Time (90th %)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "p90" ] } },
   "targets": [
    {
     "expr": "{job=\"api\"} | json | req_method =~ `.+`"
    }
   ]
  },
  {
   "title": "Api Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"api\"} | json | level = `50` | line_format `Status: {{.err_httpCode}} | {{.err_name}}: {{.err_message}}`"
    }
   ]
  },
  {
   "title": "Postgres Statements",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"postgresql\"} | json | message =~ `(statement|execute).*` | line_format `{{.timestamp}} | {{.message}}`"
    }
   ]
  },
  {
   "title": "Postgres Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"postgresql\"} | json | line_format `{{.severity}}: {{.message}}`"
    }
   ]
  }
 ]
}